trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  BROWSER: 'chrome'
  GROUPS: 'smoke'   # blank = run all
  THREADS: '3'

steps:
  - checkout: self

  # Set Java version
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'              # change to '25' only if your agent supports it
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # Run Maven tests
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: >
        -Dbrowser=$(BROWSER)
        -Dgroups=$(GROUPS)
        -Dthreads=$(THREADS)
      publishJUnitResults: false

  # Publish TestNG/Surefire XML results to ADO "Tests" tab
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/target/surefire-reports/*.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Selenium TestNG Results'
    condition: succeededOrFailed()

  # Publish reports (Extent, screenshots, logs) as Artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/test-output'  # change to your real report folder
      artifact: 'automation-reports'
      publishLocation: 'pipeline'
    condition: always()