# Sensitive credentials for API access
username=reddy.chandana20@gmail.com
password=ATATT3xFfGF0yoHr2lvd7r8v4dMOvBj2AUtaQIQfjZF12nBDcs8FvEHxREYY7UiY5jIWZvQ55WEoa6i4JuFZTg7qhSeJGJor3_ZICKj9ZZeNWcsy8qzNKYaUF5TUA5IYHkEeNSbSi28ouzpALKMqapxNJOH12xUFHN3SSi5luuUa8MBQixfA_ow=1C32FF4B
api_key=reqres_4b94b4fac0c24dbcbc8148ef90e6967f
